name: wipac ci/cd


on:
  # only on branch pushes
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'


env:
  CI_DOCKER_IMAGE_W_TAG: mqs/test:local
  #
  HERE_URL: mqs.testing-url.aq
  MONGODB_HOST: localhost
  MONGODB_PORT: 27017
  REST_HOST: localhost  # the server should connect to 0.0.0.0
  REST_PORT: 8080
  BROKER_URL: test-broker.url.aq
  BROKER_QUEUE_USERNAME: theuser
  BROKER_TYPE: rabbitmq
  BROKER_QUEUE_AUTH_PRIVATE_KEY_FILE: /test-priv-keys/broker-queue-private.key  # root dir
  BROKER_QUEUE_AUTH_PUBLIC_KEY_FILE: /test-pub-keys/broker-queue-public.key  # root dir
  #
  REST_OPENAPI_SPEC_FPATH: "schema/rest/openapi_spec.json"
  DB_JSONSCHEMA_DIR: "schema/db"


jobs:

  py-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - id: versions
        uses: WIPACrepo/wipac-dev-py-versions-action@v2.7


  #############################################################################
  # LINTERS
  #############################################################################

  flake8:
    needs: [ py-versions ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: actions/setup-python@v5
        with:
          python-version:
            ${{ matrix.py3 }}
      - uses: WIPACrepo/wipac-dev-flake8-action@v1.3
        with:
          max-complexity: 10  # ideal is ~10-15

  mypy:
    needs: [ py-versions ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
          fetch-depth: 0  # setuptools-scm needs to access git tags
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py3 }}
      - uses: WIPACrepo/wipac-dev-mypy-action@v2.0


  #############################################################################
  # PACKAGING
  #############################################################################

  py-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
      - uses: WIPACrepo/wipac-dev-py-setup-action@v5.2
        with:
          mode: PACKAGING
          python_min: 3.12
          python_max: 3.12
          keywords_comma: "EWMS, task, Workflow Management Service, WIPAC, IceCube, Observation Management Service, Event Workflow Management System"
          auto_mypy_option: True


  py-dependencies:
    runs-on: ubuntu-latest
    steps:
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: docker/setup-buildx-action@v2
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: mqs:py-dep-this
          load: true
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: WIPACrepo/wipac-dev-py-dependencies-action@v2.1


  #############################################################################
  # FORMATTER
  #############################################################################

  code-format:
    runs-on: ubuntu-latest
    steps:
      - if: github.actor != 'dependabot[bot]'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
      - name: git config
        if: github.actor != 'dependabot[bot]'
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: ruff
        if: github.actor != 'dependabot[bot]'
        run: |
          # use literal collection syntax, see https://docs.astral.sh/ruff/rules/unnecessary-collection-call/
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          pip install ruff
          ruff check --select C408 --fix . --unsafe-fixes
      - name: isort
        if: github.actor != 'dependabot[bot]'
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          pip install isort
          isort . --profile black -v --float-to-top --reverse-relative
      - name: push changes
        if: github.actor != 'dependabot[bot]'
        run: |
          # check git status
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          git fetch
          if [[ $(git status -sb | grep behind) ]]; then
            echo "this commit is not the most recent on this branch -- changes won't be pushed"
            exit 0
          else
            # push
            git add . || true
            git commit -m "<bot> auto code format file(s)" || true
            git push || true
          fi


  ############################################################################
  # AUTO-GENERATION
  #############################################################################

  schema-modifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
      - uses: WIPACrepo/wipac-dev-json-schema-action@v2.0
        with:
          rest_openapi_paths_dir: "schema-precompiled/paths"
          rest_openapi_base_fpath: "schema-precompiled/openapi_prebuild.json"
          rest_openapi_dest_fpath: "mqs/${{ env.REST_OPENAPI_SPEC_FPATH }}"
          db_jsonschema_dir: "mqs/${{ env.DB_JSONSCHEMA_DIR }}"
          dunder_paths_no_vprefix: "mqbroker-issuer__.well-known__jwks.json"
          version: 1

  api-documentation:
    needs: [ schema-modifications ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
      - uses: WIPACrepo/wipac-dev-openapi-docs-action@v1.0
        with:
          openapi_fpath: "mqs/${{ env.REST_OPENAPI_SPEC_FPATH }}"


  ############################################################################
  # TESTS
  #############################################################################

  test-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=min
          file: Dockerfile
          tags: ${{ env.CI_DOCKER_IMAGE_W_TAG }}

  integration-tests:
    needs: [ py-versions, schema-modifications ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    services:
      mongo:
        image: bitnami/mongodb:4
        ports:
          - 27017:27017
        env:
          MONGODB_REPLICA_SET_MODE: primary
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py3 }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          # cache-to: type=gha,mode=min
          file: Dockerfile
          tags: ${{ env.CI_DOCKER_IMAGE_W_TAG }}
          load: true
      - name: "pip install .[tests]"
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          pip install .[tests]
      - name: make mqbroker key file directories
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          set -ex
          sudo mkdir -p $(dirname ${{ env.BROKER_QUEUE_AUTH_PRIVATE_KEY_FILE }})
          sudo chmod -R 777 $(dirname ${{ env.BROKER_QUEUE_AUTH_PRIVATE_KEY_FILE }})
          sudo mkdir -p $(dirname ${{ env.BROKER_QUEUE_AUTH_PUBLIC_KEY_FILE }})
          sudo chmod -R 777 $(dirname ${{ env.BROKER_QUEUE_AUTH_PUBLIC_KEY_FILE }})
      - name: test (run rest server in background)
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          set -ex
          # this needs to be in the same step b/c shell exits when step is done
          docker run --network='host' --rm --name rest \
            --env HERE_URL="${{ env.HERE_URL }}" \
            --env MONGODB_HOST="${{ env.MONGODB_HOST }}" \
            --env MONGODB_PORT="${{ env.MONGODB_PORT }}" \
            --env REST_HOST="${{ env.REST_HOST }}" \
            --env REST_PORT="${{ env.REST_PORT }}" \
            $(env | grep '^BROKER_' | awk '$0="--env "$0') \
            --env REST_OPENAPI_SPEC_FPATH="${{ env.REST_OPENAPI_SPEC_FPATH }}" \
            --env DB_JSONSCHEMA_DIR="${{ env.DB_JSONSCHEMA_DIR }}" \
            --env CI="true" \
            --mount type=bind,source=$(dirname ${{ env.BROKER_QUEUE_AUTH_PRIVATE_KEY_FILE }}),target=$(dirname ${{ env.BROKER_QUEUE_AUTH_PRIVATE_KEY_FILE }}) \
            --mount type=bind,source=$(dirname ${{ env.BROKER_QUEUE_AUTH_PUBLIC_KEY_FILE }}),target=$(dirname ${{ env.BROKER_QUEUE_AUTH_PUBLIC_KEY_FILE }}) \
            ${{ env.CI_DOCKER_IMAGE_W_TAG }} &> ./rest.out &
          sleep 1  # hopefully not needed, but jic 

          pytest -vvv --exitfirst tests/integration/
      #
      - if: always()
        name: "docker logs rest || cat ./rest.out"
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          docker logs rest || cat ./rest.out


  unit-tests:
    needs: [ py-versions, schema-modifications ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py3 }}
      - name: "pip install .[tests]"
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          pip install .[tests]
      - name: test
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          pytest -vvv tests/unit/


  #############################################################################
  # GITHUB RELEASE
  #############################################################################

  release:
    # only run on main/master/default
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
    needs: [
      flake8,
      mypy,
      py-setup,
      py-versions,
      py-dependencies,
      code-format,
      schema-modifications,
      api-documentation,
      test-build-docker,
      integration-tests,
      unit-tests
    ]
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v7.34.6
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
          # repository_username: __token__
          # repository_password: ${{ secrets.PYPI_TOKEN }}
